DROP TABLE bought_together;
DROP TABLE tags;
DROP TABLE images;
DROP TABLE bundle_items;
DROP TABLE bundles;
DROP TABLE items;
DROP TABLE products;
DROP TABLE startech_admins;
DROP TABLE users;
DROP TABLE bans;

CREATE TABLE salman.products (
        id INT GENERATED BY DEFAULT AS IDENTITY, 
        base_price NUMBER(7, 0) NOT NULL, 
        discount NUMBER(5, 2), 
        released_year DATE NOT NULL, 
        rating NUMBER(2, 1), 
        PRIMARY KEY(id)
    );

CREATE TABLE salman.items (
    product_id INT, 
    stock INT NOT NULL, 
    PRIMARY KEY(product_id), 
    FOREIGN KEY(product_id) REFERENCES salman.products(id)
);

CREATE TABLE salman.bundles (
    product_id INT, 
    PRIMARY KEY(product_id),  
    FOREIGN KEY(product_id) REFERENCES salman.products(id)
);

CREATE TABLE salman.bundle_items (
    bundle_id INT, 
    item_id INT, 
    PRIMARY KEY(bundle_id, item_id), 
    FOREIGN KEY(bundle_id) REFERENCES salman.bundles(product_id),
    FOREIGN KEY(item_id) REFERENCES salman.items(product_id)
);


CREATE TABLE salman.images (
    id INT GENERATED BY DEFAULT AS IDENTITY, 
    product_id INT, 
    img_url VARCHAR2(256) NOT NULL, 
    FOREIGN KEY(product_id) REFERENCES salman.products(id)
);

CREATE TABLE salman.tags (
    tag_name VARCHAR2(256) NOT NULL, 
    product_id INT,
    PRIMARY KEY(tag_name, product_id),
    FOREIGN KEY(product_id) REFERENCES salman.products(id)
);

CREATE TABLE salman.bought_together (
    primary_item_id INT, 
    associated_item_id INT, 
    PRIMARY KEY(primary_item_id, associated_item_id), 
    FOREIGN KEY(primary_item_id) REFERENCES salman.products(id),
    FOREIGN KEY(associated_item_id) REFERENCES salman.products(id)
);

CREATE TABLE salman.startech_admins (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    admin_name VARCHAR2(256), 
    email VARCHAR2(256) NOT NULL, 
    pass_word VARCHAR2(256) NOT NULL, 
    PRIMARY KEY(id)
);

CREATE TABLE salman.users (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR2(256), 
    pass_word VARCHAR2(256), 
    user_address VARCHAR2(256), 
    PRIMARY KEY(id)
);

CREATE TABLE salman.bans (
    banned INT, 
    banned_by INT, 
    PRIMARY KEY(banned),
    FOREIGN KEY (banned) REFERENCES salman.users(id),
    FOREIGN KEY (banned_by) REFERENCES salman.startech_admins(id)
);

