DROP TABLE salman.images;
DROP TABLE salman.bans;
DROP TABLE salman.purchase_product;
DROP TABLE salman.spec_table;
DROP TABLE salman.purchase;
DROP TABLE salman.review;
DROP TABLE salman.comments;
DROP TABLE salman.bundle_products;
DROP TABLE salman.users;
DROP TABLE salman.bundles;
DROP TABLE salman.products;

CREATE TABLE salman.products (
    id INT GENERATED BY DEFAULT AS IDENTITY START WITH 10000 INCREMENT BY 1, 
    name VARCHAR2(256),
    base_price NUMBER(7, 0) NOT NULL, 
    discount NUMBER(5, 2), 
    rating NUMBER(2, 1) DEFAULT 0.0, 
    category VARCHAR2(32),
    subcategory VARCHAR2(32),
    brand VARCHAR2(32),
    stock INT, 
    PRIMARY KEY(id)
);

CREATE TABLE salman.bundles (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(256), 
    PRIMARY KEY(id)
);

CREATE TABLE salman.bundle_products (
    bundle_id INT, 
    product_id INT, 
    PRIMARY KEY(bundle_id, product_id), 
    FOREIGN KEY(bundle_id) REFERENCES salman.bundles(id),
    FOREIGN KEY(product_id) REFERENCES salman.products(id)
);

CREATE TABLE salman.images (
    product_id INT, 
    img_url VARCHAR2(256) NOT NULL, 
    PRIMARY KEY(product_id, img_url),
    FOREIGN KEY(product_id) REFERENCES salman.products(id) ON DELETE CASCADE
);

CREATE TABLE salman.users (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(256), 
    last_name VARCHAR2(256), 
    email VARCHAR2(256), 
    pass_word VARCHAR2(256), 
    phone_number VARCHAR2(256),
    user_address VARCHAR2(256), 
    PRIMARY KEY(id)
);

CREATE TABLE salman.review (
	review_id INT GENERATED BY DEFAULT AS IDENTITY,
	product_id INT,
	user_id INT,
	rating INT,
	text VARCHAR2(256),
	PRIMARY KEY(review_id), 
	FOREIGN KEY(product_id) REFERENCES salman.products(id) ON DELETE CASCADE,
	FOREIGN KEY(user_id) REFERENCES salman.users(id)
);


CREATE TABLE salman.bans (
    email VARCHAR2(256),
	ban_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY(email)
);

create table salman.comments(
	comment_id INT GENERATED BY DEFAULT AS IDENTITY, 
    product_id INT,
    comment_on INT,
    user_id INT,
	text varchar2(256),
	comment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY(comment_id),
    FOREIGN KEY (user_id) REFERENCES salman.users(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES salman.products(id) ON DELETE CASCADE,
    FOREIGN KEY (comment_on) REFERENCES salman.comments(comment_id) ON DELETE CASCADE
);

CREATE TABLE salman.purchase (
    purchase_id INT GENERATED BY DEFAULT AS IDENTITY, 
    purchase_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    approval_date TIMESTAMP DEFAULT NULL, 
    payment_info VARCHAR2(256), 
    address VARCHAR2(256), 
    bought_by INT, 
    PRIMARY KEY(purchase_id),
    FOREIGN KEY (bought_by) REFERENCES salman.users(id) ON DELETE SET NULL
);

create table salman.purchase_product(
    purchase_id INT,
    product_id INT,
    product_count INT,
    PRIMARY KEY(purchase_id, product_id),
    FOREIGN KEY (purchase_id) REFERENCES salman.purchase(purchase_id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES salman.products(id) ON DELETE CASCADE
);

CREATE TABLE salman.spec_table (
    attr_name VARCHAR2(50) NOT NULL,
    attr_value VARCHAR2(200), 
    product_id INT NOT NULL,
    FOREIGN KEY(product_id) REFERENCES salman.products(id) ON DELETE CASCADE,
    PRIMARY KEY(attr_name, product_id)
);
