-- To reset the DBs run the sql. 

DROP TABLE salman.images;
DROP TABLE salman.tags;
DROP TABLE salman.bought_together;
DROP TABLE salman.bans;
DROP TABLE salman.purchase_product;
DROP TABLE salman.spec_table;
DROP TABLE salman.purchase;
DROP TABLE salman.comments;
DROP TABLE salman.startech_admins;
DROP TABLE salman.bundle_products;
DROP TABLE salman.users;
DROP TABLE salman.bundles;
DROP TABLE salman.products;


CREATE TABLE salman.products (
        id INT GENERATED BY DEFAULT AS IDENTITY, 
        base_price NUMBER(7, 0) NOT NULL, 
        discount NUMBER(5, 2), 
        rating NUMBER(2, 1), 
        category VARCHAR2(32),
        subcategory VARCHAR2(32),
        brand VARCHAR2(32),
        stock INT, 
        PRIMARY KEY(id)
);

CREATE TABLE salman.bundles (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY(id)
);

CREATE TABLE salman.bundle_products (
    bundle_id INT, 
    product_id INT, 
    PRIMARY KEY(bundle_id, product_id), 
    FOREIGN KEY(bundle_id) REFERENCES salman.bundles(id),
    FOREIGN KEY(product_id) REFERENCES salman.products(id)
);

CREATE TABLE salman.images (
    product_id INT, 
    img_url VARCHAR2(256) NOT NULL, 
    PRIMARY KEY(product_id, img_url),
    FOREIGN KEY(product_id) REFERENCES salman.products(id)
);

CREATE TABLE salman.tags (
    tag_name VARCHAR2(256) NOT NULL, 
    product_id INT,
    PRIMARY KEY(tag_name, product_id),
    FOREIGN KEY(product_id) REFERENCES salman.products(id)
);

CREATE TABLE salman.bought_together (
    primary_item_id INT, 
    associated_item_id INT, 
    PRIMARY KEY(primary_item_id, associated_item_id), 
    FOREIGN KEY(primary_item_id) REFERENCES salman.products(id),
    FOREIGN KEY(associated_item_id) REFERENCES salman.products(id)
);

CREATE TABLE salman.startech_admins (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    admin_name VARCHAR2(256), 
    email VARCHAR2(256) NOT NULL, 
    pass_word VARCHAR2(256) NOT NULL, 
    PRIMARY KEY(id)
);

CREATE TABLE salman.users (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(256), 
    last_name VARCHAR2(256), 
    email VARCHAR2(256), 
    pass_word VARCHAR2(256), 
    phone_number VARCHAR2(256),
    user_address VARCHAR2(256), 
    PRIMARY KEY(id)
);

CREATE TABLE salman.bans (
    banned INT, 
    banned_by INT, 
    PRIMARY KEY(banned),
    FOREIGN KEY (banned) REFERENCES salman.users(id) ON DELETE CASCADE,
    FOREIGN KEY (banned_by) REFERENCES salman.startech_admins(id)
);

create table salman.comments(
    comment_id INT,
    product_id INT,
    comment_on INT,
    user_id INT,
    PRIMARY KEY(comment_id),
    FOREIGN KEY (user_id) REFERENCES salman.users(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES salman.products(id) ON DELETE CASCADE,
    FOREIGN KEY (comment_on) REFERENCES salman.comments(comment_id) ON DELETE CASCADE
);

CREATE TABLE salman.purchase (
    purchase_id INT GENERATED BY DEFAULT AS IDENTITY, 
    purchase_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    payment_info VARCHAR2(256), 
    status VARCHAR2(256) DEFAULT 0,
    PRIMARY KEY(purchase_id),
    bought_by INT, 
    verified_by INT DEFAULT NULL, 
    FOREIGN KEY (bought_by) REFERENCES salman.users(id) ON DELETE CASCADE,
    FOREIGN KEY (verified_by) REFERENCES salman.startech_admins(id)
);

create table salman.purchase_product(
    purchase_id INT,
    product_id INT,
    product_count INT,
    PRIMARY KEY(purchase_id, product_id),
    FOREIGN KEY (purchase_id) REFERENCES salman.purchase(purchase_id),
    FOREIGN KEY (product_id) REFERENCES salman.products(id)
);

CREATE TABLE salman.spec_table (
    attr_name VARCHAR2(50) not NULL,
    attr_value VARCHAR2(200), 
    product_id INT not NULL,
    FOREIGN KEY(product_id) REFERENCES salman.products(id),
    PRIMARY KEY(attr_name, product_id)
);
